---
- name: s3_log_web
  hosts: _web
  become: true
  vars_files:
          - variable.yaml
  vars:
          ansible_ssh_private_key_file: ./id_rsa
  tasks:
          - name: web logs s3 upload
            shell: sudo cp -r /var/log/httpd/ /home/ec2-user/s3bucket/web_log
            args:
                    executable: /bin/bash

- name: s3_log_web
  hosts: _was
  become: true
  vars_files:
          - variable.yaml
  vars:
          ansible_ssh_private_key_file: ./id_rsa
  tasks:
          - name: web logs s3 upload
            shell: sudo cp -r /usr/share/tomcat/logs/ /home/ec2-user/s3bucket/was_log
            args:
                    executable: /bin/bash

