---
- name: web ebs
  hosts: _web
  become: true
  vars_files:
          - variable.yaml
  vars:
          ansible_ssh_private_key_file: ./id_rsa
  tasks:
          - name: make directory ebs
            file:
                    path: /home/ec2-user/ebs
                    state: directory
          - name: mkfs -t
            shell: sudo mkfs -t xfs /dev/sdh
            args:
                    executable: /bin/bash
          - name: mount
            shell: sudo mount /dev/sdh /home/ec2-user/ebs
            args:
                    executable: /bin/bash
          - name: change owner ebs
            file:
                    dest: /home/ec2-user/ebs
                    owner: ec2-user
                    group: ec2-user
                    state: directory
